storage.storage_type.*:
  type: config_entity
  label: 'Storage type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    status:
      type: boolean
      label: 'Whether Storage items should be published by default'
    new_revision:
      type: boolean
      label: 'Whether a new revision should be created by default'
    revision_expose:
      type: boolean
      label: 'Whether to show the revision checkbox'
    revision_log:
      type: boolean
      label: 'Whether to show the revision log text field'
    uuid:
      type: string
    name_pattern:
      type: string
      label: 'A pattern to use for creating the name of the Storage entity'
